services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade
    restart: unless-stopped
    working_dir: /freqtrade
    user: "${UID}:${GID}"
    volumes:
      - ./user_data:/freqtrade/user_data
    ports:
      - "8080:8080"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    # GPU request (Compose accepts this and ignores in non-Swarm; safe to keep)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      trade
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy MyFreqAIStrategy
      --freqaimodel PyTorchRegressor
